package crud_java.Views;

import crud_java.Controllers.CitasController;
import java.awt.Color;
import javax.swing.JPanel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.ZoneId;
import java.time.LocalTime;
import javax.swing.JOptionPane;

public class AgregarActualizarCita extends javax.swing.JPanel {

    CitasController controlador;
    // Variable para saber si estamos agregando o actualizando, asi podemos reutilizar esta pantalla
    boolean agregandoCita;

    public AgregarActualizarCita(CitasController controlador, boolean agregandoCita) {
        initComponents();
        this.controlador = controlador;
        this.agregandoCita = agregandoCita;

        // Si estamos actualizando cargamos toda la informacion
        if (!agregandoCita) {
            Titulo.setText("Actualizar cita");
            buttonAgregar.setText("Actualizar");

            // Con un conversor obtenemos la fecha
            SimpleDateFormat conversorFecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date fecha = null;

            try {
                fecha = conversorFecha.parse(controlador.obtenerCitaActual().getFecha());
            } catch (ParseException ex) {
                Logger.getLogger(AgregarActualizarCita.class.getName()).log(Level.SEVERE, null, ex);
            }

            LocalDate fechaLocal = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalTime horaLocal = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();

            fechaCita.timePicker.setTime(horaLocal);
            fechaCita.datePicker.setDate(fechaLocal);
            idMedico.setText(controlador.obtenerCitaActual().getMedicoId());
            idEnfermero.setText(controlador.obtenerCitaActual().getEnfermeroId());
            idPaciente.setText(controlador.obtenerCitaActual().getPacienteId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        idPaciente = new javax.swing.JTextField();
        Text3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        idMedico = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        idEnfermero = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        buttonAgregar = new javax.swing.JButton();
        fechaCita = new com.github.lgooddatepicker.components.DateTimePicker();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo.setText("Registrar nueva cita");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("ID Paciente");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 260, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        idPaciente.setForeground(new java.awt.Color(102, 102, 102));
        idPaciente.setBorder(null);
        add(idPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 260, 30));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Fecha");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 10));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("ID Medico");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        idMedico.setForeground(new java.awt.Color(102, 102, 102));
        idMedico.setBorder(null);
        add(idMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 10));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("ID Enfermero");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        idEnfermero.setForeground(new java.awt.Color(102, 102, 102));
        idEnfermero.setBorder(null);
        add(idEnfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, 10));

        buttonAgregar.setBackground(new java.awt.Color(18, 90, 173));
        buttonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgregar.setText("Registrar");
        buttonAgregar.setBorder(null);
        buttonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseClicked(evt);
            }
        });
        add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 260, 50));
        add(fechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseClicked
        // Variable para guardar el resultado de la operacion de agregar
        boolean resultado = false;

        if (agregandoCita) {
            resultado = controlador.AgregarCita(fechaCita.toString(), idMedico.getText(), idEnfermero.getText(), idPaciente.getText());
        } else {
            resultado = controlador.ActualizarCita(fechaCita.toString(), idMedico.getText(), idEnfermero.getText(), idPaciente.getText());
        }

        // Si el resultado es verdadero, significa que se agrego con exito, si no, ocurrio un error, mostramos un mensaje en consecuencia
        if (resultado)
            JOptionPane.showMessageDialog(this, "¡Cambios registrados correctamente!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "¡Error al registrar los cambios!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonAgregarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel body;
    private javax.swing.JButton buttonAgregar;
    private com.github.lgooddatepicker.components.DateTimePicker fechaCita;
    private javax.swing.JTextField idEnfermero;
    private javax.swing.JTextField idMedico;
    private javax.swing.JTextField idPaciente;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
