package crud_java.Views;

import crud_java.Controllers.PacientesController;
import java.awt.Color;
import javax.swing.JPanel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AgregarActualizarPaciente extends javax.swing.JPanel {

    PacientesController controlador;
    // Variable para saber si estamos agregando o actualizando, asi podemos reutilizar esta pantalla
    boolean agregandoPaciente;

    public AgregarActualizarPaciente(PacientesController controlador, boolean agregandoPaciente) {
        initComponents();
        this.controlador = controlador;
        this.agregandoPaciente = agregandoPaciente;

        // Si estamos actualizando cargamos toda la informacion
        if (!agregandoPaciente) {
            Titulo.setText("Actualizar paciente");
            buttonAgregar.setText("Actualizar");

            sip.setText(controlador.getPacienteActual().getSip());
            dni.setText(controlador.getPacienteActual().getDni());
            nombre.setText(controlador.getPacienteActual().getNombre());
            apellido1.setText(controlador.getPacienteActual().getApellido1());
            apellido2.setText(controlador.getPacienteActual().getApellido2());
            telefono.setText(controlador.getPacienteActual().getTelefono());
            sexo.setSelectedItem(controlador.getPacienteActual().getSexo());

            // Con un conversor obtenemos la fecha
            SimpleDateFormat conversorFecha = new SimpleDateFormat("yyyy-MM-dd");
            Date fecha = null;

            try {
                fecha = conversorFecha.parse(controlador.getPacienteActual().getFechaNacimiento());
            } catch (ParseException ex) {
                Logger.getLogger(AgregarActualizarCita.class.getName()).log(Level.SEVERE, null, ex);
            }

            LocalDate fechaLocal = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            fechaNacimiento.setDate(fechaLocal);
            localidad.setText(controlador.getPacienteActual().getLocalidad());
            calle.setText(controlador.getPacienteActual().getCalle());
            numero.setText(controlador.getPacienteActual().getNumero());
            puerta.setText(controlador.getPacienteActual().getPuerta());
            piso.setText(controlador.getPacienteActual().getPiso());
            idMedico.setText(controlador.getPacienteActual().getMedicoId());
            idEnfermero.setText(controlador.getPacienteActual().getEnfermeroId());
            idUser.setText(controlador.getPacienteActual().getUserId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        text5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        sip = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        buttonAgregar = new javax.swing.JButton();
        dni = new javax.swing.JTextField();
        Text6 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        Text8 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        Text9 = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        localidad = new javax.swing.JTextField();
        Text11 = new javax.swing.JLabel();
        calle = new javax.swing.JTextField();
        fechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        Text12 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        Text13 = new javax.swing.JLabel();
        puerta = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        Text14 = new javax.swing.JLabel();
        piso = new javax.swing.JTextField();
        Text15 = new javax.swing.JLabel();
        idMedico = new javax.swing.JTextField();
        Text17 = new javax.swing.JLabel();
        idEnfermero = new javax.swing.JTextField();
        Text18 = new javax.swing.JLabel();
        idUser = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Titulo.setText("Registrar nuevo paciente");
        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Sexo");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 260, 0));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text5.setText("Numero colegiado");
        add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 0));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("DNI");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        sip.setBorder(null);
        sip.setForeground(new java.awt.Color(102, 102, 102));
        add(sip, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 260, 0));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Nombre");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        nombre.setBorder(null);
        nombre.setForeground(new java.awt.Color(102, 102, 102));
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 0));

        buttonAgregar.setBackground(new java.awt.Color(18, 90, 173));
        buttonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgregar.setText("Registrar");
        buttonAgregar.setBorder(null);
        buttonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseClicked(evt);
            }
        });
        add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 260, 50));

        dni.setBorder(null);
        dni.setForeground(new java.awt.Color(102, 102, 102));
        add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 130, 30));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Primer apellido");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        apellido1.setBorder(null);
        apellido1.setForeground(new java.awt.Color(102, 102, 102));
        add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 30));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Segundo apellido");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        apellido2.setBorder(null);
        apellido2.setForeground(new java.awt.Color(102, 102, 102));
        add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, 30));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Telefono");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        telefono.setBorder(null);
        telefono.setForeground(new java.awt.Color(102, 102, 102));
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 260, 30));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Fecha de nacimiento");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Localidad");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        localidad.setBorder(null);
        localidad.setForeground(new java.awt.Color(102, 102, 102));
        add(localidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 260, 30));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("Calle");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        calle.setBorder(null);
        calle.setForeground(new java.awt.Color(102, 102, 102));
        add(calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 260, 30));
        add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 160, 30));

        Text12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text12.setText("Numero");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, 20));

        numero.setBorder(null);
        numero.setForeground(new java.awt.Color(102, 102, 102));
        add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 130, 30));

        Text13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text13.setText("Puerta");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        puerta.setBorder(null);
        puerta.setForeground(new java.awt.Color(102, 102, 102));
        add(puerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 120, 30));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hombre", "mujer" }));
        add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 90, 30));

        Text14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text14.setText("Piso");
        add(Text14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, 20));

        piso.setBorder(null);
        piso.setForeground(new java.awt.Color(102, 102, 102));
        add(piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 90, 30));

        Text15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text15.setText("ID Medico");
        add(Text15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        idMedico.setBorder(null);
        idMedico.setForeground(new java.awt.Color(102, 102, 102));
        add(idMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 160, 30));

        Text17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text17.setText("ID Enfermero");
        add(Text17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, 20));

        idEnfermero.setBorder(null);
        idEnfermero.setForeground(new java.awt.Color(102, 102, 102));
        add(idEnfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 130, 30));

        Text18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text18.setText("ID Usuario");
        add(Text18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        idUser.setBorder(null);
        idUser.setForeground(new java.awt.Color(102, 102, 102));
        add(idUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseClicked
        // Variable para guardar el resultado de la operacion de agregar
        boolean resultado = false;

        if (agregandoPaciente) {
            resultado = controlador.AgregarPaciente(sip.getText(), dni.getText(), nombre.getText(), apellido1.getText(), apellido2.getText(), telefono.getText(), sexo.getSelectedItem().toString(), fechaNacimiento.toString(), localidad.getText(), calle.getText(), numero.getText(), puerta.getText(), piso.getText(), idMedico.getText(), idEnfermero.getText(), idUser.getText());
        } else {
            resultado = controlador.ActualizarPaciente(sip.getText(), dni.getText(), nombre.getText(), apellido1.getText(), apellido2.getText(), telefono.getText(), sexo.getSelectedItem().toString(), fechaNacimiento.toString(), localidad.getText(), calle.getText(), numero.getText(), puerta.getText(), piso.getText(), idMedico.getText(), idEnfermero.getText(), idUser.getText());
        }

        // Si el resultado es verdadero, significa que se agrego con exito, si no, ocurrio un error, mostramos un mensaje en consecuencia
        if (resultado) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Cambios registrados correctamente!", "Alerta", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Error al registrar los cambios!", "Alerta", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_buttonAgregarMouseClicked

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text14;
    private javax.swing.JLabel Text15;
    private javax.swing.JLabel Text17;
    private javax.swing.JLabel Text18;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JPanel body;
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JTextField calle;
    private javax.swing.JTextField dni;
    private com.github.lgooddatepicker.components.DatePicker fechaNacimiento;
    private javax.swing.JTextField idEnfermero;
    private javax.swing.JTextField idMedico;
    private javax.swing.JTextField idUser;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField localidad;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField piso;
    private javax.swing.JTextField puerta;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField sip;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel text5;
    // End of variables declaration//GEN-END:variables
}
