package crud_java.Views;

import crud_java.Controllers.MedicosController;
import java.awt.Color;
import javax.swing.JPanel;

public class AgregarActualizarMedico extends javax.swing.JPanel {

    MedicosController controlador;
    // Variable para saber si estamos agregando o actualizando, asi podemos reutilizar esta pantalla
    boolean agregandoMedico;

    public AgregarActualizarMedico(MedicosController controlador, boolean agregandoMedico) {
        initComponents();
        this.controlador = controlador;
        this.agregandoMedico = agregandoMedico;

        // Si estamos actualizando cargamos toda la informacion
        if (!agregandoMedico) {
            Titulo.setText("Actualizar medico");
            buttonAgregar.setText("Actualizar");

            numeroColegiado.setText(controlador.getMedicoActual().getNumeroColegiado());
            dni.setText(controlador.getMedicoActual().getDni());
            nombre.setText(controlador.getMedicoActual().getNombre());
            apellido1.setText(controlador.getMedicoActual().getApellido1());
            apellido2.setText(controlador.getMedicoActual().getApellido2());
            telefono.setText(controlador.getMedicoActual().getTelefono());
            sexo.setSelectedItem(controlador.getMedicoActual().getSexo());
            idEspecialidad.setText(controlador.getMedicoActual().getEspecialidadId());
            idHorario.setText(controlador.getMedicoActual().getHorarioId());
            idUser.setText(controlador.getMedicoActual().getUserId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Text3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        numeroColegiado = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        buttonAgregar = new javax.swing.JButton();
        dni = new javax.swing.JTextField();
        Text6 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        Text8 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        Text9 = new javax.swing.JLabel();
        idEspecialidad = new javax.swing.JTextField();
        Text10 = new javax.swing.JLabel();
        idHorario = new javax.swing.JTextField();
        Text11 = new javax.swing.JLabel();
        idUser = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo.setText("Registrar nuevo medico");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text2.setText("Sexo");
        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 260, 0));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        Text3.setText("Numero colegiado");
        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 0));

        Text4.setText("DNI");
        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        numeroColegiado.setForeground(new java.awt.Color(102, 102, 102));
        numeroColegiado.setBorder(null);
        add(numeroColegiado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 260, 0));

        Text5.setText("Nombre");
        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.setBorder(null);
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 0));

        buttonAgregar.setBackground(new java.awt.Color(18, 90, 173));
        buttonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgregar.setText("Registrar");
        buttonAgregar.setBorder(null);
        buttonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseClicked(evt);
            }
        });
        add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 260, 50));

        dni.setForeground(new java.awt.Color(102, 102, 102));
        dni.setBorder(null);
        add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 30));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Primer apellido");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        apellido1.setForeground(new java.awt.Color(102, 102, 102));
        apellido1.setBorder(null);
        add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, 30));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Segundo apellido");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        apellido2.setForeground(new java.awt.Color(102, 102, 102));
        apellido2.setBorder(null);
        add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 260, 30));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Telefono");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        telefono.setForeground(new java.awt.Color(102, 102, 102));
        telefono.setBorder(null);
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 260, 30));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("ID Especialidad");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        idEspecialidad.setForeground(new java.awt.Color(102, 102, 102));
        idEspecialidad.setBorder(null);
        add(idEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 260, 30));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("ID Horario");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        idHorario.setForeground(new java.awt.Color(102, 102, 102));
        idHorario.setBorder(null);
        add(idHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 260, 30));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("ID Usuario");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        idUser.setForeground(new java.awt.Color(102, 102, 102));
        idUser.setBorder(null);
        add(idUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 260, 30));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hombre", "mujer" }));
        add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 260, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseClicked
        // Variable para guardar el resultado de la operacion de agregar
        boolean resultado = false;

        if (agregandoMedico) {
            resultado = controlador.AgregarMedico(numeroColegiado.getText(), dni.getText(), nombre.getText(), apellido1.getText(), apellido2.getText(), telefono.getText(), sexo.getSelectedItem().toString(), idEspecialidad.getText(), idHorario.getText(), idUser.getText());
        } else {
            resultado = controlador.ActualizarMedico(numeroColegiado.getText(), dni.getText(), nombre.getText(), apellido1.getText(), apellido2.getText(), telefono.getText(), sexo.getSelectedItem().toString(), idEspecialidad.getText(), idHorario.getText(), idUser.getText());
        }

        // Si el resultado es verdadero, significa que se agrego con exito, si no, ocurrio un error, mostramos un mensaje en consecuencia
        if (resultado) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Cambios registrados correctamente!", "Alerta", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Error al registrar los cambios!", "Alerta", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_buttonAgregarMouseClicked

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JPanel body;
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField idEspecialidad;
    private javax.swing.JTextField idHorario;
    private javax.swing.JTextField idUser;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroColegiado;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
